tfa.inspect.creator=Créateur: %s
tfa.inspect.manufacturer=Fabricant: %s
tfa.inspect.capacity=Capacité: %s Balles
tfa.inspect.ammotype=Munitions: %s
tfa.inspect.purpose=Objectif: %s
tfa.inspect.condition=État: %s%%

tfa.inspect.stat.accuracy=Précision: %s
tfa.inspect.stat.accuracy.hip=Précision en Tir Rapide: %s
tfa.inspect.stat.rpm=Cadence de Tir: %s TR/MIN
tfa.inspect.stat.mobility=Mobilité: %s%%
tfa.inspect.stat.damage=Dégâts: %s
tfa.inspect.stat.range=Portée: %skm
tfa.inspect.stat.stability=Stabilité: %s%%
tfa.inspect.stat.bashdamage=Dégâts de Frappe: %s
tfa.inspect.damagedrop=Diminution des dégâts avec la distance

tfa.inspect.val.degrees=%.2f°
tfa.inspect.val.moa=%d MOA

tfa.hud.ammo.clip1=CHARGEUR: %s
tfa.hud.ammo.reserve1=RÉSERVE: %s
tfa.hud.ammo.clip2=CHARGEUR-ALT: %s
tfa.hud.ammo.reserve2=RÉSERVE-ALT: %s
tfa.hud.ammo1=MUNITIONS: %s
tfa.hud.ammo2=MUNITIONS-ALT: %s
tfa.hud.jammed=L'arme est enrayée!

tfa.msg.weaponjammed=Votre arme s'est enrayée. Rechargez-la.

tfa.settings.client=Côté Client
tfa.settings.server=Côté Serveur

tfa.svsettings.dryfire=Nécessite une pression sur la touche de rechargement
tfa.svsettings.dynaccuracy=Précision Dynamique
tfa.svsettings.stripempty=Retirer les Armes Vides
tfa.svsettings.ironsight=Activer les Viseurs
tfa.svsettings.sprint=Activer la Course Moderne
tfa.svsettings.attachments=Activer les Accessoires
tfa.svsettings.randomizenpcatts=Les PNJ Ont des Accessoires Aléatoires
tfa.svsettings.cmenu=Activer le Menu C Personnalisé
tfa.svsettings.penetration=Activer la Pénétration des Balles
tfa.svsettings.ricochet=Activer les Ricochets des Balles
tfa.svsettings.doorbust=Activer la Destruction des Portes par Balles
tfa.svsettings.doorbash=Activer l'Enfoncement des Portes au Corps-à-Corps
tfa.svsettings.reloads=Activer le Rechargement
tfa.svsettings.jamming=Activer l'Enrayement
tfa.svsettings.nearlyempty=Activer les Sons de Presque-Vide
tfa.svsettings.legacyreloads=Activer le Rechargement de Style Ancien
tfa.svsettings.fixedcrosshair=Fixer le Réticule au Centre de l'Écran
tfa.svsettings.crosshairshowplayer=La Couleur du Réticule Révèle les Joueurs
tfa.svsettings.crosshairshowplayerteam=La Couleur du Réticule Révèle l'Équipe du Joueur
tfa.svsettings.damagemult=Multiplicateur de Dégâts
tfa.svsettings.damagemultnpc=Multiplicateur de Dégâts pour les Armes des PNJ
tfa.svsettings.damagemultrand_min=Multiplicateur de Dégâts Aléatoire Minimum
tfa.svsettings.damagemultrand_max=Multiplicateur de Dégâts Aléatoire Maximum
tfa.svsettings.damagemultrand_tip=Multiplicateur de dégâts supplémentaire basé sur le RNG ajouté au-dessus du multiplicateur régulier. Définissez min et max à 1 pour arrêter la randomisation.
tfa.svsettings.doorrespawntime=Temps de Réapparition des Portes
tfa.svsettings.jamchance=Multiplicateur de Probabilité d'Enrayement
tfa.svsettings.jamfactormult=Multiplicateur du Facteur d'Enrayement
tfa.svsettings.jamfactorinc=Multiplicateur d'Augmentation du Facteur d'Enrayement
tfa.svsettings.forcemult=Multiplicateur de Force d'Impact
tfa.svsettings.penpowermul=Multiplicateur de Puissance de Pénétration
tfa.svsettings.spreadmult=Multiplicateur de Dispersion
tfa.svsettings.penetrationlimit=Limite du Nombre de Pénétrations
tfa.svsettings.defaultclip=Nombre de Balles par Défaut du Chargeur (-1 = par défaut)
tfa.svsettings.rangemod=Multiplicateur Maximum de Diminution des Dégâts
tfa.svsettings.randomseed=Remplir une graine RNG supplémentaire lors du tir côté serveur
tfa.svsettings.randomseed_tip=Cela causera des décalages de tirs avec le serveur. Activez-le si vous savez vraiment ce que vous faites!
tfa.svsettings.fov.sprintmod=Activer le Modificateur FOV de Course
tfa.svsettings.recoilmult=Multiplicateur de Recul
tfa.svsettings.knockbackmult=Multiplicateur de Knockback
tfa.svsettings.firstdrawanim=Activer l'Animation de Premier Tirage

tfa.sightsettings.3dscopes=Activer les Viseurs 3D
tfa.sightsettings.3dscopeshadows=Activer les Ombres des Viseurs 3D
tfa.sightsettings.3dsm=Mode de Sensibilité des Viseurs 3D
tfa.sightsettings.3dsm.nc=0 - Pas de Compensation
tfa.sightsettings.3dsm.sc=1 - Compensation Standard
tfa.sightsettings.3dsm.3d=2 - Compensation 3D
tfa.sightsettings.3dsm.rt=3 - Compensation FOV RT
tfa.sightsettings.3dsq=Qualité des Viseurs 3D
tfa.sightsettings.3dsq.at=-1 - Détection Automatique
tfa.sightsettings.3dsq.ul=0 - Haute (1x)
tfa.sightsettings.3dsq.hq=1 - Moyenne (0,5x)
tfa.sightsettings.3dsq.mq=2 - Basse (0,25x)
tfa.sightsettings.3dsq.lq=3 - Très Basse (0,125x)
tfa.sightsettings.3dsb=Mode de Flou des Viseurs 3D
tfa.sightsettings.3dsb.nb=0 - Pas de Flou
tfa.sightsettings.3dsb.sb=1 - Flou Standard
tfa.sightsettings.3dsb.bb=2 - Flou Bokeh
tfa.sightsettings.rtbgblurpasses=Qualité du Flou du Viseur
tfa.sightsettings.rtbgblurintensity=Force du Flou du Viseur
tfa.sightsettings.adstoggle=Basculer les Viseurs
tfa.sightsettings.adsresight=Conserver les Viseurs lors du Rechargement, de la Course, etc.
tfa.sightsettings.responsive=Réactif (mélange appuyé/basculé)
tfa.sightsettings.responsive_timer=Minuteur de Tenue de la Touche de Visée
tfa.sightsettings.scopesensscale=Compenser la Sensibilité du FOV
tfa.sightsettings.scopesenspct=Sensibilité du Viseur (%)

tfa.vmsettings.viewbobanim=Utiliser l'Animation du Vacillement de Vue
tfa.vmsettings.viewbobmult=Intensité du Vacillement de Vue
tfa.vmsettings.gunbobcustom=Vacillement d'Arme Personnalisé
tfa.vmsettings.gunswayinvert=Inverser la Direction du Balancement d'Arme
tfa.vmsettings.gunbobmult=Intensité du Vacillement d'Arme
tfa.vmsettings.offset.x=Décalage du Modèle de Vue - X
tfa.vmsettings.offset.y=Décalage du Modèle de Vue - Y
tfa.vmsettings.offset.z=Décalage du Modèle de Vue - Z
tfa.vmsettings.offset.fov=Décalage du Modèle de Vue - FOV
tfa.vmsettings.fovmult=Multiplicateur FOV du Modèle de Vue
tfa.vmsettings.centered=Modèle de Vue Centré
tfa.vmsettings.flip=Inverser le Modèle de Vue
tfa.vmsettings.laserdottrail=Traînées de Points Laser
tfa.vmsettings.nearwall=Décalage du Modèle de Vue Près du Mur

tfa.perfsettings.gasblur=Utiliser le Flou du Gaz
tfa.perfsettings.mzsmoke=Utiliser la Fumée du Muzzle Flash
tfa.perfsettings.mztrail=Utiliser les Traînées de Fumée du Muzzle
tfa.perfsettings.mztrail.limit=Limiter les Traînées de Fumée du Muzzle
tfa.perfsettings.ejsmoke=Utiliser la Fumée d'Éjection
tfa.perfsettings.impactfx=Utiliser les Effets d'Impact Personnalisés
tfa.perfsettings.ricochetfx=Utiliser les Effets de Ricochet
tfa.perfsettings.oldshells=Utiliser l'Éjection de Douilles Héritée
tfa.perfsettings.adsdof=Activer la Profondeur de Champ des Viseurs
tfa.perfsettings.adsdof.hd=Activer la Vraie Profondeur de Champ
tfa.perfsettings.ejlife=Durée de Vie des Douilles Éjectées
tfa.perfsettings.ricochetspark.amount=Quantité d'Étincelles de Ricochet
tfa.perfsettings.ricochetspark.life=Durée de Vie des Étincelles de Ricochet
tfa.perfsettings.penetrationdecal=Utiliser le Décalque de Pénétration

tfa.hudsettings.label=HUD
tfa.hudsettings.enabled=Utiliser le HUD Personnalisé
tfa.hudsettings.fadein=Temps d'Apparition du HUD des Munitions
tfa.hudsettings.hangtime=Temps de Maintien du HUD (après rechargement, etc.)
tfa.hudsettings.fallback=Activer le HUD de Secours Simple
tfa.hudsettings.fallback.desc=Affiché lorsque le HUD 3D2D est désactivé, pour fournir des informations essentielles avec des HUD personnalisés
tfa.hudsettings.crosshair.label=Réticule
tfa.hudsettings.crosshair.enabled=Utiliser le Réticule Personnalisé
tfa.hudsettings.crosshair.dot=Utiliser le Point du Réticule
tfa.hudsettings.crosshair.triangular=Utiliser le Réticule Triangulaire
tfa.hudsettings.crosshair.pump=Retour sur le Réticule
tfa.hudsettings.crosshair.length.usepixels=Longueur du Réticule en Pixels
tfa.hudsettings.crosshair.length=Longueur du Réticule
tfa.hudsettings.crosshair.gapscale=Échelle de l'Écart du Réticule
tfa.hudsettings.crosshair.width=Largeur du Réticule
tfa.hudsettings.crosshair.color=Couleur du Réticule
tfa.hudsettings.crosshair.teamcolor=Activer la Mise en Évidence d'Équipe du Réticule
tfa.hudsettings.crosshair.teamcolor.enemy=Couleur de Mise en Évidence d'Équipe: Ennemi
tfa.hudsettings.crosshair.teamcolor.friendly=Couleur de Mise en Évidence d'Équipe: Allié
tfa.hudsettings.crosshair.outline.enabled=Activer le Contour du Réticule
tfa.hudsettings.crosshair.outline.width=Largeur du Contour du Réticule
tfa.hudsettings.crosshair.outline.color=Couleur du Contour du Réticule
tfa.hudsettings.hitmarker.label=Marqueur de Coup
tfa.hudsettings.hitmarker.enabled=Activer le Marqueur de Coup
tfa.hudsettings.hitmarker.3d.all=Marqueur de Coup 3D pour Toutes les Armes
tfa.hudsettings.hitmarker.3d.shotguns=Marqueur de Coup 3D pour les Fusils à Pompe
tfa.hudsettings.hitmarker.solidtime=Temps Solide du Marqueur de Coup
tfa.hudsettings.hitmarker.fadetime=Temps d'Estompage du Marqueur de Coup
tfa.hudsettings.hitmarker.scale=Échelle du Marqueur de Coup
tfa.hudsettings.hitmarker.color=Couleur du Marqueur de Coup
tfa.hudsettings.scalemul=Multiplicateur de Taille du HUD
tfa.hudsettings.keybindhints.label=Indices de Touches
tfa.hudsettings.keybindhints.enabled=Activer les Indices de Touches
tfa.hudsettings.keybindhints.solidtime=Temps Solide de l'Indice
tfa.hudsettings.keybindhints.fadeintime=Temps d'Apparition de l'Indice
tfa.hudsettings.keybindhints.fadeouttime=Temps d'Estompage de l'Indice

tfa.devsettings.adminonly=AVERTISSEMENT! Ces options ne sont utiles que pour les développeurs et peuvent ralentir le jeu lorsqu'elles sont activées!
tfa.devsettings.debug.crosshair=Dessiner le Réticule de Débogage (Point)
tfa.devsettings.debug.animations=Dessiner le Statut et le Nom de l'Animation
tfa.devsettings.debug.rtshadow=Déboguer la Superposition RT
tfa.devsettings.debug.cache=Désactiver la Mise en Cache des Statistiques
tfa.devsettings.statmigrator.label=Traducteur de Noms de Statistiques
tfa.devsettings.statmigrator.help=Cet outil permet de convertir les noms de statistiques hérités en ceux utilisés avec la dernière version de données
tfa.devsettings.statmigrator.dataversion=Version de Données Actuelle (%s): %s
tfa.devsettings.statmigrator.old_name=Ancien Nom de Statistique
tfa.devsettings.statmigrator.new_name=Nouveau Nom de Statistique
tfa.devsettings.statmigrator.copy_btn.label=Copier le nouveau nom dans le presse-papiers
tfa.devsettings.documentation.label=Ceci est la documentation de référence pour les développeurs d'addons (modèles d'armes et hooks)
tfa.devsettings.documentation.btn.github=Documentation @ GitHub

tfa.colorsettings.laser=Couleur du Laser
tfa.colorsettings.reticule=Couleur du Réticule

tfa.ballisticsettings.enabled=Activer la Balistique
tfa.ballisticsettings.customgravity=Gravité personnalisée des balles
tfa.ballisticsettings.customgravityvalue=Vitesse de gravité personnalisée
tfa.ballisticsettings.mindist=Distance d'Activation (-1 = toujours)
tfa.ballisticsettings.bullet.life=Durée de Vie de la Balle
tfa.ballisticsettings.bullet.damping.air=Résistance de l'Air de la Balle
tfa.ballisticsettings.bullet.damping.water=Résistance de l'Eau de la Balle
tfa.ballisticsettings.bullet.velocity=Vitesse de la Balle
tfa.ballisticsettings.substeps=Sous-Étapes
tfa.ballisticsettings.fx.bullet=Modèles de Balles
tfa.ballisticsettings.fx.hq=Calculs de Position HQ
tfa.ballisticsettings.fx.mp=Balistique Multijoueur
tfa.ballisticsettings.fx.mptracer=Traceurs Multijoueur
tfa.ballisticsettings.tracer=Style de Traceur
tfa.ballisticsettings.tracer.di=0 - Désactivé
tfa.ballisticsettings.tracer.sm=1 - Fumant
tfa.ballisticsettings.tracer.re=2 - Rouge Vif

tfa.about.version=Version %s
tfa.about.author=Créé par %s
tfa.about.maintain=Maintenu par %s et %s
tfa.about.contributors=Contributions supplémentaires: %s
tfa.about.font=Police intégrée et utilisée:
tfa.about.changelog.label=Historique des modifications/versions:
tfa.about.changelog.btn.github=CHANGELOG.md @ GitHub
tfa.about.changelog.btn.steam=Notes de Modifications Steam

tfa.inspectsettings.inspectdof.enabled=Utiliser le DOF Bokeh d'Inspection
tfa.inspectsettings.inspectdof.radius=Rayon du DOF Bokeh
tfa.inspectsettings.hide=Masquer l'Écran d'Inspection
tfa.inspectsettings.hidehud=Masquer le HUD Lorsque l'Écran est Actif
tfa.inspectsettings.hideinscreenshots=Masquer l'Écran d'Inspection dans les Captures d'Écran
tfa.inspectsettings.newbars=Utiliser les Barres de Statistiques Plates
tfa.inspectsettings.spreadinmoa=Afficher la Dispersion en MOA

tfa.attsettings.persist=Enregistrer/Restaurer la Sélection d'Accessoires
tfa.attsettings.resetsaved.current.btn=Réinitialiser la sélection d'accessoires pour l'arme actuelle
tfa.attsettings.resetsaved.current.title=Réinitialiser la sélection d'accessoires pour %s
tfa.attsettings.resetsaved.current.text=Êtes-vous sûr de vouloir réinitialiser la sélection d'accessoires pour cette arme?\nIls seront enregistrés à nouveau une fois que vous (dé)équiperez un accessoire.
tfa.attsettings.resetsaved.all.btn=Réinitialiser la sélection d'accessoires pour TOUTES LES ARMES
tfa.attsettings.resetsaved.all.title=Réinitialiser la sélection d'accessoires pour toutes les armes
tfa.attsettings.resetsaved.all.text=Êtes-vous sûr de vouloir réinitialiser la sélection d'accessoires pour TOUTES LES ARMES?\nCette action ne peut pas être annulée.

tfa.smsettings.viewmodel=Modèle de Vue
tfa.smsettings.sights=Viseurs / Lunettes
tfa.smsettings.perf=Performance
tfa.smsettings.hud=HUD / Réticule
tfa.smsettings.dev=Développeur
tfa.smsettings.color=Personnalisation des Couleurs
tfa.smsettings.ballistics=Balistique
tfa.smsettings.server=Admin / Serveur
tfa.smsettings.keybinds=Raccourcis Clavier
tfa.smsettings.about=À Propos
tfa.smsettings.inspect=Interface d'Inspection

tfa.menubar.npcs.weapon=Remplacement d'Arme TFA

tfa.hudpreset.cross=Croix
tfa.hudpreset.crysis2=Crysis 2
tfa.hudpreset.dot=Point (Minimaliste)
tfa.hudpreset.hl2=Half-Life 2
tfa.hudpreset.hl2plus=Half-Life 2 Amélioré
tfa.hudpreset.rockstar=Rockstar (GTA V / Max Payne 3)

tfa.keybinds.help.bind=Dans ce menu, vous pouvez assigner une touche à une certaine action de base.
tfa.keybinds.help.bound=Quand une touche est assignée pour une action, la combinaison de touche par défaut pour elle est désactivée.
tfa.keybinds.help.unbind=Clic droit sur une touche pour désassigner/réinitialiser à la valeur par défaut.

tfa.keybind.bash=Frappe / Attaque Secondaire
tfa.keybind.customize=Menu Personnalisation / Statistiques
tfa.keybind.inspect=Inspecter l'Arme
tfa.keybind.firemode=Basculer le Mode de Tir
tfa.keybind.silencer=Basculer le Silencieux

tfa.firemode.safe=Sécurité
tfa.firemode.auto=Automatique
tfa.firemode.single=Tir Unique
tfa.firemode.revolver=Double-Action
tfa.firemode.bolt=Action Verrou
tfa.firemode.pump=Action Pompe
tfa.firemode.semi=Semi-Automatique
tfa.firemode.burst=Rafale de %s Coups

tfa.ammo.pistol=Pistolet Générique
tfa.ammo.smg1=Pistolet-Mitrailleur Générique
tfa.ammo.ar2=Fusil Générique
tfa.ammo.buckshot=Fusil à Pompe Générique
tfa.ammo.357=Revolver Générique
tfa.ammo.sniperpenetratedround=Sniper Générique

tfa.weptype.generic=Arme
tfa.weptype.pistol=Pistolet
tfa.weptype.machpistol=Pistolet-Mitrailleur
tfa.weptype.revolver=Revolver
tfa.weptype.smg=Pistolet-Mitrailleur
tfa.weptype.rifle=Fusil
tfa.weptype.carbine=Carabine
tfa.weptype.lmg=Mitrailleuse Légère
tfa.weptype.shotgun=Fusil à Pompe
tfa.weptype.dmr=Fusil de Précision Désigné
tfa.weptype.sniper=Fusil de Sniper
tfa.weptype.grenade=Grenade
tfa.weptype.launcher=Lance-Grenades
tfa.weptype.pistol.dual=Pistolets Jumelés
tfa.weptype.revolver.dual=Revolvers Jumelés
tfa.weptype.smg.dual=Pistolets-Mitrailleurs Jumelés
tfa.weptype.generic.dual=Armes Jumelées

tfa.keys.lmb=CGB
tfa.keys.lmb_full=Clic Gauche de la Souris
tfa.keys.rmb=CDD
tfa.keys.rmb_full=Clic Droit de la Souris
tfa.keys.mmb=CMS
tfa.keys.mmb_full=Clic Milieu de la Souris

tfa.hint.keys.ironsights=Viser avec les Viseurs
tfa.hint.keys.customize=Statistiques et Personnalisation
tfa.hint.keys.inspect=Inspecter l'Arme
tfa.hint.keys.firemode=Changer le Mode de Tir
tfa.hint.keys.safety=Basculer la Sécurité
tfa.hint.keys.silencer=Basculer le Silencieux
tfa.hint.keys.meleebash=Attaque au Corps-à-Corps
tfa.hint.keys.altattack=Attaque Secondaire
tfa.hint.keys.flashlight=Basculer la Lampe Torche
tfa.hint.keys.grenadelauncher=Basculer le Lance-Grenades
tfa.hint.keys.showkeys=Afficher cette liste

tfbow_arrow_ammo=Flèches
tfbow_bolt_ammo=Traits
SniperPenetratedRound_ammo=Munitions de Sniper
AirboatGun_ammo=Munitions Winchester
