# Inspection des armes
tfa.inspect.creator=Créateur : %s
tfa.inspect.manufacturer=Fabricant : %s
tfa.inspect.capacity=Capacité : %s Balles
tfa.inspect.ammotype=Munitions : %s
tfa.inspect.purpose=Objectif : %s
tfa.inspect.condition=État : %s%%

# Statistiques d'inspection
tfa.inspect.stat.accuracy=Précision : %s
tfa.inspect.stat.accuracy.hip=Précision en Tir Rapide : %s
tfa.inspect.stat.rpm=Cadence de Tir : %s TR/MIN
tfa.inspect.stat.mobility=Mobilité : %s%%
tfa.inspect.stat.damage=Dégâts : %s
tfa.inspect.stat.range=Portée : %s km
tfa.inspect.stat.stability=Stabilité : %s%%
tfa.inspect.stat.bashdamage=Dégâts de Frappe : %s
tfa.inspect.damagedrop=Diminution des dégâts avec la distance

# Valeurs d'inspection
tfa.inspect.val.degrees=%.2f°
tfa.inspect.val.moa=%d MOA

# HUD - Munitions
tfa.hud.ammo.clip1=CHARGEUR : %s
tfa.hud.ammo.reserve1=RÉSERVE : %s
tfa.hud.ammo.clip2=CHARGEUR ALT : %s
tfa.hud.ammo.reserve2=RÉSERVE ALT : %s
tfa.hud.ammo1=MUNITIONS : %s
tfa.hud.ammo2=MUNITIONS ALT : %s
tfa.hud.jammed=L'arme est enrayée !

# Messages
tfa.msg.weaponjammed=Votre arme est enrayée. Rechargez-la.

# Paramètres
tfa.settings.client=Côté Client
tfa.settings.server=Côté Serveur

# Paramètres Serveur
tfa.svsettings.dryfire=Demander une pression sur la touche de rechargement
tfa.svsettings.dynaccuracy=Précision Dynamique
tfa.svsettings.stripempty=Retirer les Armes Vides
tfa.svsettings.ironsight=Activer les Viseurs
tfa.svsettings.sprint=Activer la Course Moderne
tfa.svsettings.attachments=Activer les Accessoires
tfa.svsettings.randomizenpcatts=Les PNJ Ont des Accessoires Aléatoires
tfa.svsettings.cmenu=Activer le Menu C Personnalisé
tfa.svsettings.penetration=Activer la Pénétration des Balles
tfa.svsettings.ricochet=Activer les Ricochets des Balles
tfa.svsettings.doorbust=Activer la Destruction des Portes par Balles
tfa.svsettings.doorbash=Activer l'Enfoncement des Portes au Corps-à-Corps
tfa.svsettings.reloads=Activer le Rechargement
tfa.svsettings.jamming=Activer l'Enrayement
tfa.svsettings.nearlyempty=Activer les Sons de Presque-Vide
tfa.svsettings.legacyreloads=Activer le Rechargement de Style Ancien
tfa.svsettings.fixedcrosshair=Fixer le Réticule au Centre de l'Écran
tfa.svsettings.crosshairshowplayer=La Couleur du Réticule Révèle les Joueurs
tfa.svsettings.crosshairshowplayerteam=La Couleur du Réticule Révèle l'Équipe du Joueur
tfa.svsettings.damagemult=Multiplicateur de Dégâts
tfa.svsettings.damagemultnpc=Multiplicateur de Dégâts pour les Armes des PNJ
tfa.svsettings.damagemultrand_min=Multiplicateur de Dégâts Aléatoire Minimum
tfa.svsettings.damagemultrand_max=Multiplicateur de Dégâts Aléatoire Maximum
tfa.svsettings.damagemultrand_tip=Multiplicateur de dégâts supplémentaire basé sur le RNG ajouté au-dessus du multiplicateur régulier. Définissez min et max à 1 pour arrêter la randomisation.
tfa.svsettings.doorrespawntime=Temps de Réapparition des Portes
tfa.svsettings.jamchance=Multiplicateur de Probabilité d'Enrayement
tfa.svsettings.jamfactormult=Multiplicateur du Facteur d'Enrayement
tfa.svsettings.jamfactorinc=Multiplicateur d'Augmentation du Facteur d'Enrayement
tfa.svsettings.forcemult=Multiplicateur de Force d'Impact
tfa.svsettings.penpowermul=Multiplicateur de Puissance de Pénétration
tfa.svsettings.spreadmult=Multiplicateur de Dispersion
tfa.svsettings.penetrationlimit=Limite du Nombre de Pénétrations
tfa.svsettings.defaultclip=Nombre de Balles par Défaut du Chargeur (-1 = par défaut)
tfa.svsettings.rangemod=Multiplicateur Maximum de Diminution des Dégâts
tfa.svsettings.randomseed=Remplir une graine RNG supplémentaire lors du tir côté serveur
tfa.svsettings.randomseed_tip=Cela causera des décalages de tirs avec le serveur. Activez-le si vous savez vraiment ce que vous faites !
tfa.svsettings.fov.sprintmod=Activer le Modificateur FOV de Course
tfa.svsettings.recoilmult=Multiplicateur de Recul
tfa.svsettings.knockbackmult=Multiplicateur de Knockback
tfa.svsettings.firstdrawanim=Activer l'Animation de Premier Tirage

# Paramètres de Viseurs
tfa.sightsettings.3dscopes=Activer les Viseurs 3D
tfa.sightsettings.3dscopeshadows=Activer les Ombres des Viseurs 3D
tfa.sightsettings.3dsm=Mode de Sensibilité des Viseurs 3D
tfa.sightsettings.3dsm.nc=0 - Pas de Compensation
tfa.sightsettings.3dsm.sc=1 - Compensation Standard
tfa.sightsettings.3dsm.3d=2 - Compensation 3D
tfa.sightsettings.3dsm.rt=3 - Compensation FOV RT
tfa.sightsettings.3dsq=Qualité des Viseurs 3D
tfa.sightsettings.3dsq.at=-1 - Détection Automatique
tfa.sightsettings.3dsq.ul=0 - Haute (1x)
tfa.sightsettings.3dsq.hq=1 - Moyenne (0,5x)
tfa.sightsettings.3dsq.mq=2 - Basse (0,25x)
tfa.sightsettings.3dsq.lq=3 - Très Basse (0,125x)
tfa.sightsettings.3dsb=Mode de Flou des Viseurs 3D
tfa.sightsettings.3dsb.nb=0 - Pas de Flou
tfa.sightsettings.3dsb.sb=1 - Flou Standard
tfa.sightsettings.3dsb.bb=2 - Flou Bokeh
tfa.sightsettings.rtbgblurpasses=Qualité du Flou du Viseur
tfa.sightsettings.rtbgblurintensity=Force du Flou du Viseur
tfa.sightsettings.adstoggle=Basculer les Viseurs
tfa.sightsettings.adsresight=Conserver les Viseurs lors du Rechargement, de la Course, etc.
tfa.sightsettings.responsive=Réactif (mélange appuyé/basculé)
tfa.sightsettings.responsive_timer=Minuteur de Tenue de la Touche de Visée
tfa.sightsettings.scopesensscale=Compenser la Sensibilité du FOV
tfa.sightsettings.scopesenspct=Sensibilité du Viseur (%)

# Paramètres du Modèle de Vue
tfa.vmsettings.viewbobanim=Utiliser l'Animation du Vacillement de Vue
tfa.vmsettings.viewbobmult=Intensité du Vacillement de Vue
tfa.vmsettings.gunbobcustom=Vacillement d'Arme Personnalisé
tfa.vmsettings.gunswayinvert=Inverser la Direction du Balancement d'Arme
tfa.vmsettings.gunbobmult=Intensité du Vacillement d'Arme
tfa.vmsettings.offset.x=Décalage du Modèle de Vue - X
tfa.vmsettings.offset.y=Décalage du Modèle de Vue - Y
tfa.vmsettings.offset.z=Décalage du Modèle de Vue - Z
tfa.vmsettings.offset.fov=Décalage du Modèle de Vue - FOV
tfa.vmsettings.fovmult=Multiplicateur FOV du Modèle de Vue
tfa.vmsettings.centered=Modèle de Vue Centré
tfa.vmsettings.flip=Inverser le Modèle de Vue
tfa.vmsettings.laserdottrail=Traînées de Points Laser
tfa.vmsettings.nearwall=Décalage du Modèle de Vue Près du Mur

# Paramètres de Performance
tfa.perfsettings.gasblur=Utiliser le Flou du Gaz
tfa.perfsettings.mzsmoke=Utiliser la Fumée du Muzzle Flash
tfa.perfsettings.mztrail=Utiliser les Traînées de Fumée du Muzzle
tfa.perfsettings.mztrail.limit=Limiter les Traînées de Fumée du Muzzle
tfa.perfsettings.ejsmoke=Utiliser la Fumée d'Éjection
tfa.perfsettings.impactfx=Utiliser les Effets d'Impact Personnalisés
tfa.perfsettings.ricochetfx=Utiliser les Effets de Ricochet
tfa.perfsettings.oldshells=Utiliser l'Éjection de Douilles Héritée
tfa.perfsettings.adsdof=Activer la Profondeur de Champ des Viseurs
tfa.perfsettings.adsdof.hd=Activer la Vraie Profondeur de Champ
tfa.perfsettings.ejlife=Durée de Vie des Douilles Éjectées
tfa.perfsettings.ricochetspark.amount=Quantité d'Étincelles de Ricochet
tfa.perfsettings.ricochetspark.life=Durée de Vie des Étincelles de Ricochet
tfa.perfsettings.penetrationdecal=Utiliser le Décalque de Pénétration

# Types d'Armes
tfa.weptype.generic=Arme
tfa.weptype.pistol=Pistolet
tfa.weptype.machpistol=Pistolet-Mitrailleur
tfa.weptype.revolver=Revolver
tfa.weptype.smg=Pistolet-Mitrailleur
tfa.weptype.rifle=Fusil
tfa.weptype.carbine=Carabine
tfa.weptype.lmg=Mitrailleuse Légère
tfa.weptype.shotgun=Fusil à Pompe
tfa.weptype.dmr=Fusil de Précision Désigné
tfa.weptype.sniper=Fusil de Sniper
tfa.weptype.grenade=Grenade
tfa.weptype.launcher=Lance-Grenades
tfa.weptype.pistol.dual=Pistolets Jumelés
tfa.weptype.revolver.dual=Revolvers Jumelés
tfa.weptype.smg.dual=Pistolets-Mitrailleurs Jumelés
tfa.weptype.generic.dual=Armes Jumelées

# Touches du Clavier
tfa.keys.lmb=CGB
tfa.keys.lmb_full=Clic Gauche de la Souris
tfa.keys.rmb=CDD
tfa.keys.rmb_full=Clic Droit de la Souris
tfa.keys.mmb=CMS
tfa.keys.mmb_full=Clic Milieu de la Souris

# Indices de Touches
tfa.hint.keys.ironsights=Viser avec les Viseurs
tfa.hint.keys.customize=Statistiques et Personnalisation
tfa.hint.keys.inspect=Inspecter l'Arme
tfa.hint.keys.firemode=Changer le Mode de Tir
tfa.hint.keys.safety=Basculer la Sécurité
tfa.hint.keys.silencer=Basculer le Silencieux
tfa.hint.keys.meleebash=Attaque au Corps-à-Corps
tfa.hint.keys.altattack=Attaque Secondaire
tfa.hint.keys.flashlight=Basculer la Lampe Torche
tfa.hint.keys.grenadelauncher=Basculer le Lance-Grenades
tfa.hint.keys.showkeys=Afficher cette liste

# Munitions
tfbow_arrow_ammo=Flèches
tfbow_bolt_ammo=Traits
SniperPenetratedRound_ammo=Munitions de Sniper
AirboatGun_ammo=Munitions Winchester
